name: Package extension
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate schema
        run: glib-compile-schemas --strict --dry-run schemas
      - name: Package
        run: ./tools/package.sh
      - uses: actions/upload-artifact@v4
        with:
          name: ttfx-idle-screensaver-extension
          path: dist/*.zip
